version: "3.9"
services:
    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: s3cret!
            POSTGRES_USER: shook
            POSTGRES_DB: shook
        expose:
            - "5432"
        volumes:
            - "./db-data:/var/lib/postgresql/data"

    shook-server:
        image: shook-server:latest
        restart: always
        ports:
            - "80:80"
        environment:
            DB_SERVER: db
            DB_PORT: 5432
            DB_NAME: shook
            DB_USER: shook
            DB_PASSWORD: s3cret!
        links:
            - "db"