// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Database;

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210512201333_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Model.ShookDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Shooks");
                });

            modelBuilder.Entity("Model.UserShookDto", b =>
                {
                    b.Property<int>("UserDtoId")
                        .HasColumnType("integer");

                    b.Property<int>("ShookDtoId")
                        .HasColumnType("integer");

                    b.HasKey("UserDtoId", "ShookDtoId");

                    b.HasIndex("ShookDtoId");

                    b.ToTable("UserShooks");
                });

            modelBuilder.Entity("Server.Models.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.ShookDto", b =>
                {
                    b.HasOne("Server.Models.UserDto", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("Server.Models.UserDto", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Creator");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Model.UserShookDto", b =>
                {
                    b.HasOne("Model.ShookDto", "Shook")
                        .WithMany("ShookUsers")
                        .HasForeignKey("ShookDtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.UserDto", "User")
                        .WithMany("UserShooks")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.ShookDto", b =>
                {
                    b.Navigation("ShookUsers");
                });

            modelBuilder.Entity("Server.Models.UserDto", b =>
                {
                    b.Navigation("UserShooks");
                });
#pragma warning restore 612, 618
        }
    }
}
